### ISSUE TITLE
Tiempo de descarga

### ISSUE THREAD

**Issue by alexcortes90** [MovistarTV/tv_grab_es_movistartv#16]
Tengo una simple duda,
Lleva descargando la epg durante casi 2 horas, es eso normal?
En el caso de que si cuanto suele tardar?

**Comment by alexcortes90** [comment]
por lo que veo en la carpeta programs tengo info de cosas de junio de 2019

**Comment by alexcortes90** [comment]
Esto es una mierda , no para de descargar y mo genera nada

**Comment by alexcortes90** [comment]
Perdona por el comentario anterior pero es que estoy muy frustrado con el tema
Ahora me da este error critico  
Me podrias ayudar?

[07/03/2019 20:08:13] [CRITICAL] not all arguments converted during string formatting
Traceback (most recent call last):
  File "tv_grab_es_movistartv.py", line 1205, in <module>
    epg = iptv.get_epg()
  File "tv_grab_es_movistartv.py", line 783, in get_epg
    return self.__parse_bin_epg()
  File "tv_grab_es_movistartv.py", line 892, in __parse_bin_epg
    programs[str(head['service_id'])] = self.__parse_bin_epg_body(head['data'])
  File "tv_grab_es_movistartv.py", line 869, in __parse_bin_epg_body
    logger.error('Error al procesar la guía: %s' % ex.args)
TypeError: not all arguments converted during string formatting

**Comment by MovistarTV** [comment]
Voy a hacer como que el comentario que acabo de borrar nunca a existido.

Dicho eso: sí, puede ser normal.

Empieza revisando el log.

**Comment by alexcortes90** [comment]
El problema es que se me queda en 
[INFO] Generando la guía XMLTV: descargando info extendida
Durante toda la noche y no hace nada

**Comment by MovistarTV** [comment]
> Ahora me da este error critico

Esa excepción está enmascarado otra y está saltando al intentar mostrar el error real, ya está arreglado. 

Tiene que haber sido algo puntual porque el grabber funciona bien, acabo de comprobarlo.

> El problema es que se me queda en
> [INFO] Generando la guía XMLTV: descargando info extendida
> Durante toda la noche y no hace nada

Edita el script. Cambia:

`log_level = logging.INFO`

por:

`log_level = logging.DEBUG`

Y lanza el grabber. Así verás si está haciendo algo o no...

**Comment by alexcortes90** [comment]
Si, esta descargando info extendida
Cuanto tiempo suele tardar en  generar una epg de 3 dias?

**Comment by MovistarTV** [comment]
Depende de la configuración de tu red, de la calidad de tu conexión, de los servidores de Movistar, de la cantidad de canales que tengas contratados...

Mira a ver en el log qué pone la línea `tvPackages`

**Comment by alexcortes90** [comment]
UTX4X|UTX6C

**Comment by MovistarTV** [comment]
La configuración la lee bien, no estás descargando toda la guía... ¿ves timeouts en el log al descargar la información extendida?

Sobre el tiempo de descarga de la guía:

> [07/03/2019 21:19:27] [INFO] ---------------------------------------------------
> [07/03/2019 21:19:27] [INFO] MovistarTV EPG Grabber
> [07/03/2019 21:19:27] [INFO] Parámetros: ['--tvheadend', '/home/hts/MovistarTV']
> [07/03/2019 21:19:27] [INFO] ---------------------------------------------------
> [07/03/2019 21:19:27] [INFO] Cookie: JSESSIONID=DFC4B536A461B80AA7A8FBA1A4282EC9-node4; Path=/appserver/; HttpOnly
> [07/03/2019 21:19:27] [INFO] Descargando configuración del cliente
> [07/03/2019 21:19:27] [INFO] Descargando pefil del servicio
> [07/03/2019 21:19:27] [INFO] Descargando parámetros de configuración
> [07/03/2019 21:19:28] [INFO] tvPackages: UTXBV|UTXC3|UTXCP
> [07/03/2019 21:19:28] [INFO] Demarcation: 13
> [07/03/2019 21:19:28] [INFO] Descargando mapa de géneros
> [07/03/2019 21:19:28] [INFO] Buscando el Proveedor de Servicios de Asturias
> [07/03/2019 21:19:29] [INFO] Proveedor de Servicios de Asturias: 239.0.2.150
> [07/03/2019 21:19:29] [INFO] Descargando canales, paquetes e índices
> [07/03/2019 21:22:08] [INFO] Canales: 397
> [07/03/2019 21:22:08] [INFO] Paquetes: 305
> [07/03/2019 21:22:08] [INFO] Días de EPG: 8
> [07/03/2019 21:22:08] [INFO] Multithread: 3 descargas simultáneas
> [07/03/2019 21:22:08] [INFO] Descargando EPG_0_BIN.imagenio.es
> [07/03/2019 21:22:08] [INFO] Descargando EPG_1_BIN.imagenio.es
> [07/03/2019 21:22:08] [INFO] Descargando EPG_2_BIN.imagenio.es
> [07/03/2019 21:22:45] [INFO] Descargando EPG_3_BIN.imagenio.es
> [07/03/2019 21:22:47] [INFO] Descargando EPG_4_BIN.imagenio.es
> [07/03/2019 21:22:48] [INFO] Descargando EPG_5_BIN.imagenio.es
> [07/03/2019 21:23:21] [INFO] Descargando EPG_6_BIN.imagenio.es
> [07/03/2019 21:23:23] [INFO] Descargando EPG_7_BIN.imagenio.es
> [07/03/2019 21:23:59] [INFO] Generando la guía XMLTV: descargando info extendida
> [07/03/2019 22:23:46] [INFO] Lista de canales exportada: /home/hts/MovistarTV
> [07/03/2019 22:23:48] [INFO] EPG de 199 canales y 8 días descargada en 64 minutos

A mí me tarda alrededor de una hora con Fusión Selección 1 X4 600Mb, con ONT y OpenWRT en x86-64.

**Comment by alexcortes90** [comment]
Desde las 21:12 lleva descargando todavia sigue

**Comment by Yonoesio** [comment]
A mi me suele tardar entre 10 y 15 min con fibra 600/600. Ayer la generó sin problemas.

**Comment by alexcortes90** [comment]
Ya he conseguido sacar una :)
Como puedo hacer para sacar todos los canales pero solo los de HD?

**Comment by MovistarTV** [comment]
El grabber obtiene la guía en función de la configuración de Movistar, no es personalizable.
