### ISSUE TITLE
Iconos de los canales

### ISSUE THREAD

**Issue by MPAndrew** [MovistarTV/tv_grab_es_movistartv#17]
Hola. Ante todo agradecerte y felicitarte por tu trabajo. Llevo usando el grabber ya un tiempo y va perfecto, pero desde hace un tiempo he notado que no aparecen los logos de los canales cuando antes si aparecían. He actualizado el grabber por si hubiera cambiado algo y ha vuelto a descargar la guía completa pero nada, no aparecen los logos. ¿Ha cambiado algo?

Un saludo y gracias de antemano.

**Comment by Yonoesio** [comment]
Yo los veo sin problemas.

**Comment by MovistarTV** [comment]
Es cosa de TVHeadend. Hace unos meses cambiaron la URL de los logos y, si no has creado un Bouquet que gestione y actualice la lista de canales, seguirás con los logos antiguos.

La URI nueva tiene esta pinta:
http://www-60.svc.imagenio.telefonica.net:2001/appclientv/nux/incoming/epg/channelLogo/2543.jpg

Ve a `Configuration -> Channel / EPG -> Channels` y mira a ver la columna `User icon`.

**Comment by MPAndrew** [comment]
Tengo las URL nuevas, exactamente igual que la que pones. Por ejemplo, esta es la de Antena 3 HD:
http://www-60.svc.imagenio.telefonica.net:2001/appclientv/nux/incoming/epg/channelLogo/2524.jpg

Hice lo que detallas de borrar la caché y crear de nuevo la lista de canales pero los logos no me aparecen, no se por qué. De qué se trata eso de crear un Bouquet?

Gracias.

**Comment by MPAndrew** [comment]
Solucionado, era fallo mío con la configuración.

Saludos y muchas gracias.
