### ISSUE TITLE
Duda emisiones nuevas y repetidas

### ISSUE THREAD

**Issue by Yonoesio** [MovistarTV/tv_grab_es_movistartv#18]
Buenas, 

Solo una  duda. Movistar facilita la información sobre si una emision es nueva o repetida?

Un saludo

**Comment by MovistarTV** [comment]
Creo que no, en cuanto pueda te lo confirmo.

**Comment by MovistarTV** [comment]
No, no envían la fecha de la primera emisión ni hay un atributo que la marque como nueva o repetida:

Serie:
[http://www-60.svc.imagenio.telefonica.net:2001/appserver/mvtv.do?action=epgInfo&extra=1&channelID=14&productID=48413840](http://www-60.svc.imagenio.telefonica.net:2001/appserver/mvtv.do?action=epgInfo&extra=1&channelID=14&productID=48413840)

Película:
[http://www-60.svc.imagenio.telefonica.net:2001/appserver/mvtv.do?action=epgInfo&extra=1&channelID=14&productID=48413845](http://www-60.svc.imagenio.telefonica.net:2001/appserver/mvtv.do?action=epgInfo&extra=1&channelID=14&productID=48413845)

**Comment by Yonoesio** [comment]
OK. Gracias!
