### ISSUE TITLE
Faltan canales en la lista m3u

### ISSUE THREAD

**Issue by Yonoesio** [MovistarTV/tv_grab_es_movistartv#26]
Buenas,

Se genera la lista sin errores pero me faltan canales (Champions). Los tengo contratados y si cargo rtp://@239.0.3.100:8208 en VLC el canal se ve, pero no se por que motivo en el m3u no aparece...

Alguna idea?

Gracias!

**Comment by MovistarTV** [comment]
El grabber selecciona los canales en función de los paquetes que envía Movistar:

`tvPackages: UTXC3|UTXCP|UTXF9`

Cada paquete tiene una serie de canales asociados y el grabber los incluye todos. Si hubiese algún problema deberías ver algo en el log (`log_level = logging.DEBUG`)

En el deco los ves todos, ¿no?

**Comment by Yonoesio** [comment]
Curioso... He hablado con el 1004. Efectivamente no lo tengo contratado y por eso no me carga en el deco ni en la guia.

**Comment by Cebeerre** [comment]
Yo tenía la Champions + El Partidazo, y recientemente recibí una carta donde me lo cambiaban por La Liga + El Partidazo, y como a ti me desaparecieron los canales de la Champions.  Lo curioso, es que a raíz de tu mensaje, también he probado de abrir el stream RTP de los canales de la champions, y funciona :) 

Igual estaría bien @MovistarTV que añadieras alguna opción en tu script para poder poner algunos canales manualmente (como una especie de whitelist), para que se baje la EPG y lo meta en el m3u, para mientras dure :)

**Comment by Yonoesio** [comment]
Ya... Es curioso... A ver lo que dura jeje

**Comment by MovistarTV** [comment]
> Igual estaría bien @MovistarTV que añadieras alguna opción en tu script para poder poner algunos canales manualmente (como una especie de whitelist), para que se baje la EPG y lo meta en el m3u, para mientras dure :)

Lo siento, pero no. Lo he dicho muchas veces... el objetivo es causar el menor impacto posible a los servidores de Movistar. El grabber sólo descarga lo que hay en la configuración del cliente, nada más.

Pero... teniendo en cuenta que la guía Multicast siempre se descarga completa, sí que me he planteado permitir generar una guía básica de todo. Y ahora que lo dices, podría ser una lista de canales extra.

Pero apenas tengo tiempo, no prometo nada a corto plazo.
