### ISSUE TITLE
Están tocando algo de nuevo?

### ISSUE THREAD

**Issue by Yonoesio** [MovistarTV/tv_grab_es_movistartv#27]
Buenas,

Desde hace un par de días no me cargan las caratulas de los programas. Están tocando algo?

Gracias!!

**Comment by MovistarTV** [comment]
Eso parece, lo estoy mirando ahora.

**Comment by Cebeerre** [comment]
A mi me funciona ... 

Lo que me fallaba hace unos días, es que un programa venía con un age_ratting = 11, y la lista que está declarada en el Python petaba pq no había entrada con ese índice. Añadí un par o tres más con 18 en el indice y a correr ... pero era raro.

Por cierto, ya se que esto no es un foro, pero no veo Cuatro HD, están mandando ahora el stream cifrado como en los canales UHD ?

Thanks !

**Comment by MovistarTV** [comment]
Pues sí... alguien estuvo jugando con los EndPoint:

`ERROR: CCurlFile::Stat - Failed: Timeout was reached(28) for http://www-zonafoa60.svc.imagenio.telefonica.net:2010/appclientv/nux/incoming/epg/covers/programmeImages/portrait/290x429/4922/49224373.jpg`

La URI apunta al dominio `www-zonafoa60.svc.imagenio.telefonica.net`, pero no responde y Kodi no puede descargar las imágenes.

Ahora mismo `RES_BASE_URI` vuelve a apuntar a `www-60.svc.imagenio.telefonica.net`. Si borras la caché y descargas la guía deberías volver a ver las carátulas.

> Lo que me fallaba hace unos días, es que un programa venía con un age_ratting = 11, y la lista que está declarada en el Python petaba pq no había entrada con ese índice. Añadí un par o tres más con 18 en el indice y a correr ... pero era raro.

No he visto nada así... pero tened en cuenta que yo descargo la guía y hago las pruebas sobre la demarcación de Asturias y lo que hay aquí no coincide al 100% con lo que hay en las demás.

Creía que el problema que comentaban en #24 era causado por algún canal de fútbol (yo no los tengo) pero no, he sido incapaz de reproducirlo. En mi demarcación no había ese problema.

> Por cierto, ya se que esto no es un foro, pero no veo Cuatro HD, están mandando ahora el stream cifrado como en los canales UHD ?

Sí... y espero que sea otro error, porque sino me voy.

Sólo estoy en Movistar porque puedo ver la señal en todas las TV de la casa sin tener que alquilar decodificadores. Pero si lo cifran me cambio, no tiene sentido pagar más por lo mismo.

**Comment by Yonoesio** [comment]
Perfecto. Arreglado!

**Comment by Cebeerre** [comment]
> Sólo estoy en Movistar porque puedo ver la señal en todas las TV de la casa sin tener que alquilar decodificadores. Pero si lo cifran me cambio, no tiene sentido pagar más por lo mismo.

Pienso exactamente lo mismo, yo tengo el Kodi en 4 teles de la casa y veo la tele así ... Quizá no usaría Kodi+TVHeadend si por la App oficial salieran los canales Autonómicos o los de Satélite abiertos, pero por alguna extraña razón, via App no les da la gana y eso que la App si vas a los ajustes es capaz de detectar que estás en casa y no por 4G o alguna otra wifi ...
