### ISSUE TITLE
Nuevo error al generar la lista.

### ISSUE THREAD

**Issue by Yonoesio** [MovistarTV/tv_grab_es_movistartv#38]
Desde hace días no se actualiza la m3u.

>         Traceback (most recent call last):
>   File "/home/hts/.hts/tvheadend/movistartv/tv_grab_es_movistartv.py", line 1200, in <module>
>     export_channels(args.output)
>   File "/home/hts/.hts/tvheadend/movistartv/tv_grab_es_movistartv.py", line 1162, in export_channels
>     xmltv.write_m3u(m3u_file)
>   File "/home/hts/.hts/tvheadend/movistartv/tv_grab_es_movistartv.py", line 1046, in write_m3u
>     m3u = self.__generate_m3u()
>   File "/home/hts/.hts/tvheadend/movistartv/tv_grab_es_movistartv.py", line 1070, in __generate_m3u
>     channel_key = self.__channels[self.__channels[channel_id]['replacement']]['id']
> KeyError: u'4745'

Tambien me he fijado que ha desaparecido "La1 HD" de la lista.

**Comment by MovistarTV** [comment]
Perdona que haya tardado tanto, desde que codificaron los canales no he vuelto a usar el grabber.

Tiene pinta de que fue algo puntual, lo mismo que pasó aquí: #24
