### ISSUE TITLE
Problemas de ejecucion

### ISSUE THREAD

**Issue by Yonoesio** [MovistarTV/tv_grab_es_movistartv#6]
SOLUCIONADO. 

Era cosa de la config del router...

----------------------------------------------------------------------

Hola de nuevo
Parece que soy el unico con problemas...
Desde hace unos días estoy ejecutando el script y da error. Primero con la codificación. Me pego con UTF-8, pero lo cambio y parace que funciona, aunque cuando detecta la ñ casca y tengo que cambiarlo a n.

Pero el que no consigo solucionar, más que nada porque no tengo ni idea de python es el siguiente:
`Excepcion:

         'NoneType' object has no attribute '__getitem__'

Traceback:

        Traceback (most recent call last):
  File "tv_grab_es_movistartv.py", line 1172, in <module>
    xdata = iptv.get_service_provider_data()
  File "tv_grab_es_movistartv.py", line 798, in get_service_provider_data
    self.__get_epg_data(connection['mcast_grp'], connection['mcast_port'])
  File "tv_grab_es_movistartv.py", line 790, in __get_epg_data
    'channels': self.__get_channels(xml['2_0']),
TypeError: 'NoneType' object has no attribute '__getitem__'
`
Tienes alguna idea? He provado con la versión 2.7, 3.4, 3.5, 3.6 .......
Gracias por tu ayuda

**Comment by MovistarTV** [comment]
Hola,

Me alegro de que lo hayas resuelto. Simplemente comentar que el script sólo funciona con Python 2.

Un saludo.
